# Generated by Django 3.2.6 on 2021-08-10 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': '주연배우', 'verbose_name_plural': '주연배우 목록'},
        ),
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movist.actor', verbose_name='주연배우'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='desc',
            field=models.TextField(verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='', verbose_name='포스터 이미지'),
        ),
    ]
